# Labels canonical list for Lichtara Codex
# (This file is for documentation / automation tools — use the script below to apply)
labels:
  - name: "docs"
    color: "0366d6"
    description: "Alterações na documentação"
  - name: "chore"
    color: "6f42c1"
    description: "Tarefas de manutenção e infraestrutura"
  - name: "needs-review"
    color: "fbca04"
    description: "Solicita revisão ativa"
  - name: "privacy:internal"
    color: "0e8a16"
    description: "Conteúdo interno da equipe"
  - name: "privacy:public"
    color: "1d76db"
    description: "Conteúdo público"
  - name: "privacy:private"
    color: "b60205"
    description: "Conteúdo privado / confidencial"
  - name: "size:small"
    color: "0e8a16"
    description: "Mudança pequena"
  - name: "size:medium"
    color: "fbca04"
    description: "Mudança de porte médio"
  - name: "size:large"
    color: "d93f0b"
    description: "Mudança grande"
  - name: "enhancement"
    color: "a2eeef"
    description: "Melhoria/feature"
  - name: "bug"
    color: "d73a4a"
    description: "Bug / defeito"
  - name: "good first issue"
    color: "7057ff"
    description: "Boa primeira tarefa para novos contribuidores"
  - name: "help wanted"
    color: "008672"
    description: "Precisamos de ajuda externa"
  - name: "blocked"
    color: "000000"
    description: "Bloqueado por dependência/pendência"
